# Numpy - Utkarsh Gaikwad

# Numpy Part 1

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [4]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [7]:
type(np.asarray(l))

numpy.ndarray

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [10]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [11]:
arr.ndim

1

In [12]:
arr1.ndim

2

In [17]:
mat = np.matrix(l)
mat

matrix([[1, 2, 3, 4, 5]])

In [16]:
type(np.matrix(l))

numpy.matrix

In [18]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [19]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
a = arr

In [22]:
a

array([1, 2, 3, 4, 5])

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
arr[0] = 100

In [25]:
arr

array([100,   2,   3,   4,   5])

In [26]:
a

array([100,   2,   3,   4,   5])

In [27]:
b = np.copy(arr)

In [28]:
b[0] = 234

In [29]:
b

array([234,   2,   3,   4,   5])

In [30]:
arr

array([100,   2,   3,   4,   5])

In [31]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [33]:
np.fromfunction(lambda i,j : (i**2 + j**2)**0.5, (3,3))

array([[0.        , 1.        , 2.        ],
       [1.        , 1.41421356, 2.23606798],
       [2.        , 2.23606798, 2.82842712]])

In [37]:
list((i*i for i in range(100)))

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801]

In [40]:
%%timeit
list((i*i for i in range(10000)))

807 µs ± 6.41 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [41]:
%%timeit
iterable = (i*i for i in range(10000))
np_arr = np.fromiter(iterable,int)

1.32 ms ± 6.67 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [44]:
iterable = (i*i for i in range(10))
np_arr = np.fromiter(iterable,int)
np_arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [46]:
np.fromstring('23 45 67 89',sep=" ")

array([23., 45., 67., 89.])

In [47]:
np.fromstring('23,45,67,89',sep=",")

array([23., 45., 67., 89.])

In [48]:
arr

array([100,   2,   3,   4,   5])

In [49]:
arr.size

5

In [50]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr1.size

6

In [52]:
arr.shape

(5,)

In [53]:
arr1.shape

(2, 3)

In [54]:
arr.dtype

dtype('int64')

In [55]:
arr1.dtype

dtype('int64')

# Numpy part 2

In [56]:
list(range(5))

[0, 1, 2, 3, 4]

In [57]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [60]:
np.arange(0.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [61]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [62]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [64]:
np.logspace(1,5,10,base=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [65]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [71]:
np.zeros((3,4,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [72]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [73]:
arr = np.ones((3,4))

In [74]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [75]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [77]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [79]:
arr1 = np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
import pandas as pd
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [82]:
np.random.rand(2,3)

array([[0.25580341, 0.09406419, 0.25131942],
       [0.03728795, 0.93869085, 0.1435763 ]])

In [83]:
np.random.randn(2,3)

array([[ 0.37627015,  0.309532  ,  0.24004578],
       [-0.7388388 , -1.16779278, -0.1527714 ]])

In [85]:
arr2 = np.random.randint(1,5,(4,3))
arr2

array([[4, 4, 1],
       [2, 1, 4],
       [3, 3, 1],
       [4, 3, 1]])

In [86]:
arr2.size

12

In [87]:
arr2.shape

(4, 3)

In [88]:
arr2.reshape(3,4)

array([[4, 4, 1, 2],
       [1, 4, 3, 3],
       [1, 4, 3, 1]])

In [89]:
arr2.reshape(6,2)

array([[4, 4],
       [1, 2],
       [1, 4],
       [3, 3],
       [1, 4],
       [3, 1]])

In [90]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [91]:
arr2.reshape(2,6)

array([[4, 4, 1, 2, 1, 4],
       [3, 3, 1, 4, 3, 1]])

In [92]:
arr2.reshape(4,-1)

array([[4, 4, 1],
       [2, 1, 4],
       [3, 3, 1],
       [4, 3, 1]])

In [93]:
arr2.reshape(4,-1312312)

array([[4, 4, 1],
       [2, 1, 4],
       [3, 3, 1],
       [4, 3, 1]])

In [94]:
arr2.reshape(2,2,3)

array([[[4, 4, 1],
        [2, 1, 4]],

       [[3, 3, 1],
        [4, 3, 1]]])

In [95]:
arr2.reshape(2,2,3,1)

array([[[[4],
         [4],
         [1]],

        [[2],
         [1],
         [4]]],


       [[[3],
         [3],
         [1]],

        [[4],
         [3],
         [1]]]])

In [96]:
arr3 = np.random.randint(1,10,(5,6))

In [97]:
arr3

array([[5, 9, 7, 4, 2, 2],
       [3, 3, 9, 9, 7, 3],
       [8, 9, 4, 1, 5, 6],
       [6, 4, 9, 6, 6, 7],
       [7, 5, 1, 1, 4, 2]])

In [99]:
arr3>8

array([[False,  True, False, False, False, False],
       [False, False,  True,  True, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False]])

In [100]:
arr3[arr3>8]

array([9, 9, 9, 9, 9])

In [101]:
arr3

array([[5, 9, 7, 4, 2, 2],
       [3, 3, 9, 9, 7, 3],
       [8, 9, 4, 1, 5, 6],
       [6, 4, 9, 6, 6, 7],
       [7, 5, 1, 1, 4, 2]])

In [104]:
arr3[0,0:2]

array([5, 9])

In [105]:
arr3[2:4,3:5]

array([[1, 5],
       [6, 6]])

In [107]:
arr4 = np.random.randint(1,3,(3,3))
arr5 = np.random.randint(1,3,(3,3))

In [108]:
arr4

array([[2, 1, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [109]:
arr5

array([[2, 1, 2],
       [1, 1, 1],
       [1, 1, 1]])

In [110]:
arr4+arr5

array([[4, 2, 3],
       [2, 3, 2],
       [3, 3, 2]])

In [111]:
arr4-arr5

array([[ 0,  0, -1],
       [ 0,  1,  0],
       [ 1,  1,  0]])

In [112]:
arr4*arr5

array([[4, 1, 2],
       [1, 2, 1],
       [2, 2, 1]])

In [113]:
arr4@arr5

array([[6, 4, 6],
       [5, 4, 5],
       [7, 5, 7]])

In [114]:
arr4/arr5

array([[1. , 1. , 0.5],
       [1. , 2. , 1. ],
       [2. , 2. , 1. ]])

In [115]:
arr4/0

/tmp/ipykernel_70/1674986024.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [116]:
# Numpy Broadcasting

In [117]:
arr6 =np.zeros((3,4))

In [118]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [119]:
arr6 + 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [122]:
a = np.array([1,2,3,4])

In [123]:
arr6 + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [127]:
b = np.array([[3,4,5]])

In [129]:
arr7 = arr6 + b.T

In [130]:
arr7

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [131]:
np.sqrt(arr7)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [132]:
np.log10(arr7)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [133]:
np.exp(arr7)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [134]:
np.min(arr7)

3.0

In [135]:
np.max(arr7)

5.0

In [136]:
np.mean(arr7)

4.0

In [137]:
np.std(arr7)

0.816496580927726

# Numpy - Part 3

In [138]:
# Numpy array manipulation

In [140]:
arr = np.random.randint(1,10,(4,4))
arr 

array([[7, 8, 6, 7],
       [5, 3, 3, 7],
       [3, 8, 2, 1],
       [2, 3, 5, 7]])

In [141]:
arr.reshape(8,2)

array([[7, 8],
       [6, 7],
       [5, 3],
       [3, 7],
       [3, 8],
       [2, 1],
       [2, 3],
       [5, 7]])

In [142]:
arr.T

array([[7, 5, 3, 2],
       [8, 3, 8, 3],
       [6, 3, 2, 5],
       [7, 7, 1, 7]])

In [143]:
arr.flatten()

array([7, 8, 6, 7, 5, 3, 3, 7, 3, 8, 2, 1, 2, 3, 5, 7])

In [144]:
arr.ravel()

array([7, 8, 6, 7, 5, 3, 3, 7, 3, 8, 2, 1, 2, 3, 5, 7])

In [145]:
np.expand_dims(arr,axis=1)

array([[[7, 8, 6, 7]],

       [[5, 3, 3, 7]],

       [[3, 8, 2, 1]],

       [[2, 3, 5, 7]]])

In [146]:
np.expand_dims(arr,axis=0)

array([[[7, 8, 6, 7],
        [5, 3, 3, 7],
        [3, 8, 2, 1],
        [2, 3, 5, 7]]])

In [147]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [148]:
np.squeeze(data)

array([1, 2, 3])

In [150]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [152]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [153]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [154]:
# numpy binary operations

In [155]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [156]:
arr1

array([[7, 9, 1, 4],
       [8, 8, 3, 5],
       [8, 3, 9, 4]])

In [157]:
arr2

array([[3, 2, 3, 7],
       [2, 4, 9, 4],
       [8, 1, 9, 6]])

In [158]:
arr1 + arr2

array([[10, 11,  4, 11],
       [10, 12, 12,  9],
       [16,  4, 18, 10]])

In [159]:
arr1*arr2

array([[21, 18,  3, 28],
       [16, 32, 27, 20],
       [64,  3, 81, 24]])

In [161]:
arr1/arr2

array([[2.33333333, 4.5       , 0.33333333, 0.57142857],
       [4.        , 2.        , 0.33333333, 1.25      ],
       [1.        , 3.        , 1.        , 0.66666667]])

In [162]:
arr1@arr2.T

array([[ 70,  75,  98],
       [ 84,  95, 129],
       [ 85, 125, 172]])

In [163]:
arr1-arr2

array([[ 4,  7, -2, -3],
       [ 6,  4, -6,  1],
       [ 0,  2,  0, -2]])

In [164]:
arr1**arr2

array([[      343,        81,         1,     16384],
       [       64,      4096,     19683,       625],
       [ 16777216,         3, 387420489,      4096]])

In [165]:
~arr1

array([[ -8, -10,  -2,  -5],
       [ -9,  -9,  -4,  -6],
       [ -9,  -4, -10,  -5]])

In [166]:
arr1>arr2

array([[ True,  True, False, False],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [167]:
# Numpy String Functions

In [170]:
arr1 = np.array(['utkarsh','gaikwad'])
arr1

array(['utkarsh', 'gaikwad'], dtype='<U7')

In [171]:
np.char.upper(arr1)

array(['UTKARSH', 'GAIKWAD'], dtype='<U7')

In [172]:
np.char.title(arr1)

array(['Utkarsh', 'Gaikwad'], dtype='<U7')

In [173]:
np.char.capitalize(arr1)

array(['Utkarsh', 'Gaikwad'], dtype='<U7')

In [174]:
# Numpy Math functions

In [177]:
arr2

array([[3, 2, 3, 7],
       [2, 4, 9, 4],
       [8, 1, 9, 6]])

In [178]:
np.sin(arr2)

array([[ 0.14112001,  0.90929743,  0.14112001,  0.6569866 ],
       [ 0.90929743, -0.7568025 ,  0.41211849, -0.7568025 ],
       [ 0.98935825,  0.84147098,  0.41211849, -0.2794155 ]])

In [179]:
np.cos(arr2)

array([[-0.9899925 , -0.41614684, -0.9899925 ,  0.75390225],
       [-0.41614684, -0.65364362, -0.91113026, -0.65364362],
       [-0.14550003,  0.54030231, -0.91113026,  0.96017029]])

In [180]:
np.tan(arr2)

array([[-0.14254654, -2.18503986, -0.14254654,  0.87144798],
       [-2.18503986,  1.15782128, -0.45231566,  1.15782128],
       [-6.79971146,  1.55740772, -0.45231566, -0.29100619]])

In [181]:
np.tanh(arr2)

array([[0.99505475, 0.96402758, 0.99505475, 0.99999834],
       [0.96402758, 0.9993293 , 0.99999997, 0.9993293 ],
       [0.99999977, 0.76159416, 0.99999997, 0.99998771]])

In [182]:
np.log10(arr2)

array([[0.47712125, 0.30103   , 0.47712125, 0.84509804],
       [0.30103   , 0.60205999, 0.95424251, 0.60205999],
       [0.90308999, 0.        , 0.95424251, 0.77815125]])

In [183]:
np.exp(arr2)

array([[2.00855369e+01, 7.38905610e+00, 2.00855369e+01, 1.09663316e+03],
       [7.38905610e+00, 5.45981500e+01, 8.10308393e+03, 5.45981500e+01],
       [2.98095799e+03, 2.71828183e+00, 8.10308393e+03, 4.03428793e+02]])

In [184]:
np.power(arr2,2)

array([[ 9,  4,  9, 49],
       [ 4, 16, 81, 16],
       [64,  1, 81, 36]])

In [185]:
np.mean(arr2)

4.833333333333333

In [186]:
np.median(arr2)

4.0

In [188]:
np.std(arr2)

2.733536577809454

In [189]:
np.var(arr2)

7.472222222222222

In [190]:
np.min(arr2)

1

In [191]:
np.max(arr2)

9

In [192]:
# Numpy Arithmetic operations

In [193]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [194]:
np.subtract(arr1,arr2)

array([[-6, -6,  6,  0],
       [ 2,  0,  1,  3],
       [ 1,  1, -1,  3]])

In [195]:
np.multiply(arr1,arr2)

array([[16, 16, 16, 36],
       [24, 36, 72, 28],
       [72, 56,  6, 40]])

In [197]:
np.mod(arr1,arr2)

array([[2, 2, 0, 0],
       [2, 0, 1, 3],
       [1, 1, 2, 3]])

In [198]:
np.power(arr1,arr2)

array([[     256,      256,       64,    46656],
       [    1296,    46656, 43046721,     2401],
       [43046721,  2097152,        8,    32768]])

In [199]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 2.82842712, 2.44948974],
       [2.44948974, 2.44948974, 3.        , 2.64575131],
       [3.        , 2.82842712, 1.41421356, 2.82842712]])

# Numpy Part 4

In [200]:
# Sort , Search and Counting

In [202]:
arr = np.array([4,2,8,5,9,12,11,3,23])

In [203]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 11, 12, 23])

In [205]:
np.searchsorted(arr,6)

2

In [206]:
arr1 = np.array([0,12123,21123,0,0,0,0,0,2312,0,213,0])

In [207]:
np.count_nonzero(arr1)

4

In [208]:
np.where(arr1>0)

(array([ 1,  2,  8, 10]),)

In [210]:
np.extract(arr>5,arr)

array([ 8,  9, 12, 11, 23])

In [211]:
# Numpy Byte Swapping

In [213]:
arr

array([ 4,  2,  8,  5,  9, 12, 11,  3, 23])

In [214]:
arr.byteswap()

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  648518346341351424,  864691128455135232,
        792633534417207296,  216172782113783808, 1657324662872342528])

In [215]:
# Numpy copies and views

In [216]:
a = np.copy(arr1)

In [218]:
b = arr1.view()

In [219]:
b[0] = 234

In [220]:
arr1

array([  234, 12123, 21123,     0,     0,     0,     0,     0,  2312,
           0,   213,     0])

In [221]:
# Numpy Matrix library
import numpy.matlib as nm

In [223]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [224]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [225]:
nm.eye(3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [226]:
# Numpy Linear Algebra

In [227]:
arr1

array([  234, 12123, 21123,     0,     0,     0,     0,     0,  2312,
           0,   213,     0])

In [228]:
arr1 = np.random.randint(1,10,(2,2))
arr2 = np.random.randint(1,10,(2,2))

In [229]:
arr1

array([[9, 2],
       [5, 3]])

In [230]:
arr2

array([[4, 5],
       [3, 7]])

In [231]:
np.dot(arr1,arr2)

array([[42, 59],
       [29, 46]])

In [232]:
arr1@arr2

array([[42, 59],
       [29, 46]])